roles:
    user:
        name: 'user'
        description: 'Standard authenticated user with basic permissions'
        permissions:
            - path: /auth/logout
              methods: [GET]
            - path: /auth/authorize
              methods: [GET]
            - path: /env
              methods: [GET]
            - path: /me/permissions
              methods: [GET]
            - path: /roles
              methods: [GET]
            - path: /users/*
              methods: [GET]
            - path: /users
              methods: [GET]
            - path: /me
              methods: [GET]
            - path: /votes
              methods: [GET]
            - path: /votes/*
              methods: [GET]
            - path: /votes/*/submit
              methods: [POST]
            - path: /votes/*/results
              methods: [GET]
            - path: /tournaments
              methods: [GET]
            - path: /tournaments/{id_or_slug}
              methods: [GET]

    basic_admin:
        name: 'basic_admin'
        description: 'User who can create and manage voting sessions'
        inherits: [user]
        permissions:
            - path: /votes/{id}/live
              methods: [GET]
            - path: /tournaments/{id}/admin
              methods: [POST]
            - path: /tournaments/{id}/admin/{admin_id}
              methods: [PATCH]
            - path: /tournaments/{id}/admin/{admin_id}
              methods: [DELETE]

    vote_admin:
        name: 'vote_admin'
        description: 'User who can create and manage voting sessions'
        inherits: [basic_admin]
        permissions:
            - path: /votes
              methods: [POST]
            - path: /votes/*
              methods: [PATCH]
            - path: /votes/*
              methods: [DELETE]
            - path: /votes/*/components
              methods: [POST]
            - path: /components/*
              methods: [PATCH]
            - path: /components/*
              methods: [DELETE]

    tournament_admin:
        name: 'tournament_admin'
        description: 'User who can manage and create Tournaments'
        inherits: [basic_admin]
        permissions:
            - path: /tournaments
              methods: [POST]

    super_admin:
        name: 'super_admin'
        description: 'Full system administrator with all permissions'
        inherits: [basic_admin]
        permissions:
            - path: '*'
              methods: ['*']
